---
name: Autoupdate cpanfile

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
    paths:
      - ".github/workflows/autoupdate-cpanfile.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      # runner environment
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: 'refs/heads/main'
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libidn-dev

      # perl environment
      - uses: shogo82148/actions-setup-perl@49c14f24551d2de3bf56fb107a869c3760b1875e # v1.33.0
        with:
          perl-version: '5.38'
          install-modules-with: carton
          install-modules: App::UpdateCPANfile

      - name: Update cpanfile
        id: update-cpanfile
        run: |
          test ! -f cpanfile.snapshot || rm cpanfile.snapshot
          carton install

          {
            echo "date=$(date +%Y-%m-%d)"
            echo 'msg<<.....'
            echo "### Update cpanfile at $(date +%Y-%m-%d)"
            echo
            carton exec update-cpanfile update | perl -lnpe 's<- ([a-zA-Z0-9:]+)><- [$1](https://metacpan.org/pod/$1) ==>'
            echo
            echo '---'
            echo 'This pull request made by GitHub Actions'
            echo
            echo '.....'
          } >> $GITHUB_OUTPUT

      - uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7.0.7
        with:
          title: 'Bump cpanfile at ${{ steps.update-cpanfile.outputs.date }}'
          commit-message: 'chore(cpanfile): update cpanfile at ${{ steps.update-cpanfile.outputs.date }}'
          body: ${{ steps.update-cpanfile.outputs.msg }}
          branch: 'update-cpanfile-at-${{ steps.update-cpanfile.outputs.date }}'
          add-paths: cpanfile
