---
name: Autoupdate cpanfile

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
    paths:
      - ".github/workflows/autoupdate-cpanfile.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      # runner environment
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: 'refs/heads/main'
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libidn-dev

      # perl environment
      - uses: shogo82148/actions-setup-perl@28eae78d12c2bba1163aec45d123f6d9228bc307 # v1.29.0
        with:
          perl-version: '5.38'
          install-modules-with: carton
          install-modules: App::UpdateCPANfile

      - name: Update cpanfile
        id: update-cpanfile
        run: |
          test ! -f cpanfile.snapshot || rm cpanfile.snapshot
          carton install

          {
            echo "date=$(date +%Y-%m-%d)"
            echo 'msg<<.....'
            echo "### Update cpanfile at $(date +%Y-%m-%d)"
            echo
            carton exec update-cpanfile update | perl -lnpe 's<- ([a-zA-Z0-9:]+)><- [$1](https://metacpan.org/pod/$1) ==>'
            echo
            echo '---'
            echo 'This pull request made by GitHub Actions'
            echo
            echo '.....'
          } >> $GITHUB_OUTPUT

      - uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          title: 'Bump cpanfile at ${{ steps.update-cpanfile.outputs.date }}'
          commit-message: 'chore(cpanfile): update cpanfile at ${{ steps.update-cpanfile.outputs.date }}'
          body: ${{ steps.update-cpanfile.outputs.msg }}
          branch: 'update-cpanfile-at-${{ steps.update-cpanfile.outputs.date }}'
          add-paths: cpanfile
