name: Update CPAN module manually

permissions: {}

on:
  workflow_dispatch:
    inputs:
      module:
        description: CPAN module
        required: true

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  bump-cpanfile:
    name: Bump cpanfile
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write # Needs to create a pull request for CPAN module update
      pull-requests: write # Needs to create a pull request for CPAN module update
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nyarla/bump-cpanfile/update-cpan-module@ea6206481b6e1532d30b4ba84e2ad587f00cbd9b
        with:
          module: "${{ inputs.module }}"
