name: Update CPAN modules by schedule.

permissions: {}

on:
  schedule:
    - cron: "45 16 * * 5"
  workflow_dispatch: {}

env:
  perl-version: "5.44"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  matrix:
    name: Setup update matrix
    outputs:
      modules: "${{ steps.matrix.outputs.modules }}"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shogo82148/actions-setup-perl@53e33bb27be492a926eee378e8a5f7ff6618b061 # v1.43.1
        with:
          perl-version: ${{ env.perl-version }}
          enable-modules-cache: true
          install-modules-with: cpm
          install-modules-args: App::UpdateCPANfile
      - name: Make update matrix
        id: matrix
        run: |
          {
            echo -n "modules="
            update-cpanfile update cpanfile --output=json
          } >> "$GITHUB_OUTPUT"

  create-pull-requests:
    name: Create pull requests
    if: >-
      needs.matrix.outputs.modules != '' && needs.matrix.outputs.modules != '[]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write # Needs to create a pull request for CPAN module update
      pull-requests: write # Needs to create a pull request for CPAN module update
    needs:
      - matrix
    strategy:
      matrix:
        module: "${{ fromJson(needs.matrix.outputs.modules) }}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # ghasec-ignore: missing-sha-ref-comment
      - uses: nyarla/bump-cpanfile/update-cpan-module@ea6206481b6e1532d30b4ba84e2ad587f00cbd9b
        with:
          module: "${{ matrix.module.package_name }}"
