name: Update CPAN module manually.

env:
  perl-version: "5.40"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      module:
        description: The updating module name.
        type: string
        required: true

jobs:
  bump-cpanfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/composite/update-cpan-module
        with:
          perl-version: ${{ inputs.perl-version }}
          module: ${{ inputs.module }}
