---
name: Tests for p5-Kalaclista

on:
  pull_request:
    paths:
      - ".github/workflows/perl-test.yml"
      - "cpanfile"
      - "lib/**"
      - "t/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libidn-dev

      # perl environment
      - uses: shogo82148/actions-setup-perl@f551dafcc94572adc179bbddbb409b3ada8f8ff5 # v1.30.0
        with:
          perl-version: '5.38'
          install-modules-with: cpm
          install-modules-args: '-L extlib'

      # testing
      - name: Run tests
        run: |
          prove -Iextlib/lib/perl5 -Ilib -It/lib -vr t/
