---
name: Tests for p5-Kalaclista

on:
  pull_request:
    paths:
      - ".github/workflows/perl-test.yml"
      - "cpanfile"
      - "lib/**"
      - "t/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libidn-dev

      # perl environment
      - uses: shogo82148/actions-setup-perl@b87d1e37759952f1474fdac8a45d6996cf3d5512 # v1.32.0
        with:
          perl-version: '5.38'
          install-modules-with: cpm
          install-modules-args: '-L extlib'

      # testing
      - name: Run tests
        run: |
          prove -Iextlib/lib/perl5 -Ilib -It/lib -vr t/
