---
name: Tests for p5-Kalaclista

on:
  pull_request:
    paths:
      - ".github/workflows/perl-test.yml"
      - "cpanfile"
      - "lib/**"
      - "t/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libidn-dev

      # perl environment
      - uses: shogo82148/actions-setup-perl@28eae78d12c2bba1163aec45d123f6d9228bc307 # v1.29.0
        with:
          perl-version: '5.38'
          install-modules-with: cpm
          install-modules-args: '-L extlib'

      # testing
      - name: Run tests
        run: |
          prove -Iextlib/lib/perl5 -Ilib -It/lib -vr t/
